version: "3.9"

name: "vpn"

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8890
    volumes:
      - static_volume:/opt/vpn/static
      - media_volume:/opt/vpn/media
    env_file:
      - .env_prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8890 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - db_data_volume:/var/lib/postgresql/data/
    env_file:
      - .env_prod
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 30s
      timeout: 2s
      retries: 5
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/opt/vpn/static
      - media_volume:/opt/vpn/media
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/vpn/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always


volumes:
  db_data_volume:
    name: vpn_data
  static_volume:
    name: vpn_static
  media_volume:
    name: vpn_media