# Generated by Django 4.1.7 on 2023-11-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnUsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('page_transitions', models.IntegerField(default=0)),
                ('data_volume_sent', models.BigIntegerField(default=0)),
                ('data_volume_received', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
